# Generated by Django 4.0.5 on 2022-06-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0003_alter_vacancy_date_publik'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='date_time',
            field=models.TextField(blank=True, verbose_name='time_publication'),
        ),
    ]
