# Generated by Django 4.0.5 on 2022-06-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0004_vacancy_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='vis',
            field=models.BooleanField(default=True),
        ),
    ]
