from django import forms

class PhotoFilterForm(forms.Form):
    form = (('jpg', 'JPG'),
            ('jpeg', 'JPEG'),
            ('cr', 'Kodak: CR'),
            ('k25', 'Kodak: K25'),
            ('kdc', 'Kodak: KDC'),
            ('crw', 'Canon: CRW'),
            ('cr2', 'Canon: CR2'),
            ('cr3', 'Canon: CR3'),
            ('erf', 'Epson: ERF'),
            ('nef', 'Nikon: NEF'),
            ('nrw', 'Nikon: NRW'),
            ('orf', 'Olympus: ORF'),
            ('pef', 'Pentax: PEF'),
            ('rw2', 'Panasonic: RW2'),
            ('arw', 'Sony: ARW'),
            ('srf', 'Sony: SRF'),
            ('sr2', 'Sony: SR2'))
    wat = (('quality','Качество фотографий'),
           ('eyes', 'Открытые глаза'))

    wath = forms.ChoiceField(choices=wat, label='Выберите критерии фильтрации',widget=forms.Select(attrs={'class': 'form-control'}))
    put = forms.CharField(label='Путь к папке с фотографиями',widget=forms.TextInput(attrs={'placeholder': 'Путь', 'class': 'form-control'}))
    format = forms.ChoiceField(choices=form, label='Расширение файлов',widget=forms.Select(attrs={'class': 'form-control'}))

class PhotoFaceFilterForm(forms.Form):
    form = (('jpg', 'JPG'),
            ('jpeg', 'JPEG'),
            ('cr', 'Kodak: CR'),
            ('k25', 'Kodak: K25'),
            ('kdc', 'Kodak: KDC'),
            ('crw', 'Canon: CRW'),
            ('cr2', 'Canon: CR2'),
            ('cr3', 'Canon: CR3'),
            ('erf', 'Epson: ERF'),
            ('nef', 'Nikon: NEF'),
            ('nrw', 'Nikon: NRW'),
            ('orf', 'Olympus: ORF'),
            ('pef', 'Pentax: PEF'),
            ('rw2', 'Panasonic: RW2'),
            ('arw', 'Sony: ARW'),
            ('srf', 'Sony: SRF'),
            ('sr2', 'Sony: SR2'))

    detect = (('person', 'PERSON - ЧЕЛОВЕК'),
('bicycle', 'BICYCLE - ВЕЛОСИПЕД'),
('car', 'CAR - АВТОМОБИЛЬ'),
('motorcycle', 'MOTORCYCLE - МОТОЦИКЛ'),
('airplane', 'AIRPLANE - САМОЛЕТ'),
('bus', 'BUS - АВТОБУС'),
('train', 'TRAIN - ПОЕЗД'),
('truck', 'TRUCK - ГРУЗОВИК'),
('boat', 'BOAT - ЛОДКА'),
('trafficlight', 'TRAFFICLIGHT - СВЕТОФОР'),
('firehydrant', 'FIREHYDRANT - ПОЖАРНЫЙ ГИДРАНТ'),
('stopsign', 'STOPSIGN - СТОП-СИГНАЛ'),
('parkingmeter', 'PARKINGMETER - ПАРКОВОЧНЫЙ СЧЕТЧИК'),
('bench', 'BENCH - СКАМЕЙКА'),
('bird', 'BIRD - ПТИЦА'),
('cat', 'CAT - КОШКА'),
('dog', 'DOG - СОБАКА'),
('horse', 'HORSE - ЛОШАДЬ'),
('sheep', 'SHEEP - ОВЦА'),
('cow', 'COW - КОРОВА'),
('elephant', 'ELEPHANT - -СЛОН'),
('bear', 'BEAR - МЕДВЕДЬ'),
('zebra', 'ZEBRA - ЗЕБРА'),
('giraffe', 'GIRAFFE - ЖИРАФ'),
('backpack', 'BACKPACK - РЮКЗАК'),
('umbrella', 'UMBRELLA - ЗОНТИК'),
('handbag', 'HANDBAG - СУМКА'),
('tie', 'TIE - ГАЛСТУК'),
('suitcase', 'SUITCASE - ЧЕМОДАН'),
('frisbee', 'FRISBEE - ФРИСБИ'),
('skis', 'SKIS - ЛЫЖИ'),
('snowboard', 'SNOWBOARD - СНОУБОРД'),
('sportsball', 'SPORTSBALL - СПОРТИВНЫЙ МЯЧ'),
('kite', 'KITE - ВОЗДУШНЫЙ ЗМЕЙ'),
('baseballbat', 'BASEBALLBAT - БЕЙСБОЛЬНАЯ БИТА'),
('baseballglove', 'BASEBALLGLOVE - BASEBALLGLOVE'),
('skateboard', 'SKATEBOARD - СКЕЙТБОРД'),
('surfboard', 'SURFBOARD - ДОСКА ДЛЯ СЕРФИНГА'),
('tennisracket', 'TENNISRACKET - ТЕННИСНАЯ РАКЕТКА'),
('bottle', 'BOTTLE - БУТЫЛКА'),
('wineglass', 'WINEGLASS - БОКАЛ ДЛЯ ВИНА'),
('cup', 'CUP - ЧАШКА'),
('fork', 'FORK - ВИЛКА'),
('knife', 'KNIFE - НОЖ'),
('spoon', 'SPOON - ЛОЖКА'),
('bowl', 'BOWL - МИСКА'),
('banana', 'BANANA - С БАНАНОМ'),
('apple', 'APPLE - ЯБЛОКО'),
('sandwich', 'SANDWICH - СЭНДВИЧ'),
('orange', 'ORANGE - ОРАНЖЕВЫЙ'),
('broccoli', 'BROCCOLI - БРОККОЛИ'),
('carrot', 'CARROT - МОРКОВЬ'),
('hotdog', 'HOTDOG - ХОТ-ДОГ'),
('pizza', 'PIZZA - ПИЦЦА'),
('donut', 'DONUT - ПОНЧИК'),
('cake', 'CAKE - ТОРТ'),
('chair', 'CHAIR - КРЕСЛО'),
('couch', 'COUCH - ДИВАН'),
('pottedplant', 'POTTEDPLANT - КОМНАТНОЕ РАСТЕНИЕ'),
('bed', 'BED - КРОВАТЬ'),
('diningtable', 'DININGTABLE - ОБЕДЕННЫЙ СТОЛ'),
('toilet', 'TOILET - ТУАЛЕТ'),
('tv', 'TV - ТЕЛЕВИЗОР'),
('laptop', 'LAPTOP - НОУТБУК'),
('mouse', 'MOUSE - МЫШЬ'),
('remote', 'REMOTE - УДАЛЕННЫЙ'),
('keyboard', 'KEYBOARD - КЛАВИАТУРА'),
('cellphone', 'CELLPHONE - МОБИЛЬНЫЙ ТЕЛЕФОН'),
('microwave', 'MICROWAVE - МИКРОВОЛНОВАЯ ПЕЧЬ'),
('oven', 'OVEN - ДУХОВКА'),
('toaster', 'TOASTER - ТОСТЕР'),
('sink', 'SINK - РАКОВИНА'),
('refrigerator', 'REFRIGERATOR - ХОЛОДИЛЬНИК'),
('book', 'BOOK - КНИГА'),
('clock', 'CLOCK - ЧАСЫ'),
('vase', 'VASE - ВАЗА'),
('scissors', 'SCISSORS - НОЖНИЦЫ'),
('teddybear', 'TEDDYBEAR - ПЛЮШЕВЫЙ МИШКА'),
('hairdrier', 'HAIRDRIER - ПАРИКМАХЕР'),
('toothbrush', 'TOOTHBRUSH - ЗУБНАЯ ЩЁТКА'),
)
    put = forms.CharField(label='Путь к папке с фотографиями',
                          widget=forms.TextInput(attrs={'placeholder': 'Путь', 'class': 'form-control'}))
    format = forms.ChoiceField(choices=form, label='Расширение файлов',
                               widget=forms.Select(attrs={'class': 'form-control'}))
    cat = forms.ChoiceField(choices=detect, label='Категория детекции',
                            widget=forms.Select(attrs={'class': 'form-control'}))

