from django import forms

class PhotoFilterForm(forms.Form):
    form = (('jpg', 'JPG'),
            ('jpeg', 'JPEG'),
            ('cr', 'Kodak: CR'),
            ('k25', 'Kodak: K25'),
            ('kdc', 'Kodak: KDC'),
            ('crw', 'Canon: CRW'),
            ('cr2', 'Canon: CR2'),
            ('cr3', 'Canon: CR3'),
            ('erf', 'Epson: ERF'),
            ('nef', 'Nikon: NEF'),
            ('nrw', 'Nikon: NRW'),
            ('orf', 'Olympus: ORF'),
            ('pef', 'Pentax: PEF'),
            ('rw2', 'Panasonic: RW2'),
            ('arw', 'Sony: ARW'),
            ('srf', 'Sony: SRF'),
            ('sr2', 'Sony: SR2'))
    wat = (('quality','Качество фотографий'),
           ('eyes', 'Открытые глаза'))

    wath = forms.ChoiceField(choices=wat, label='Выберите критерии фильтрации',widget=forms.Select(attrs={'class': 'form-control'}))
    put = forms.CharField(label='Путь к папке с фотографиями',widget=forms.TextInput(attrs={'placeholder': 'Путь', 'class': 'form-control'}))
    format = forms.ChoiceField(choices=form, label='Расширение файлов',widget=forms.Select(attrs={'class': 'form-control'}))

class PhotoFaceFilterForm(forms.Form):
    form = (('jpg', 'JPG'),
            ('jpeg', 'JPEG'),
            ('cr', 'Kodak: CR'),
            ('k25', 'Kodak: K25'),
            ('kdc', 'Kodak: KDC'),
            ('crw', 'Canon: CRW'),
            ('cr2', 'Canon: CR2'),
            ('cr3', 'Canon: CR3'),
            ('erf', 'Epson: ERF'),
            ('nef', 'Nikon: NEF'),
            ('nrw', 'Nikon: NRW'),
            ('orf', 'Olympus: ORF'),
            ('pef', 'Pentax: PEF'),
            ('rw2', 'Panasonic: RW2'),
            ('arw', 'Sony: ARW'),
            ('srf', 'Sony: SRF'),
            ('sr2', 'Sony: SR2'))

    detect = ((0, 'PERSON - ЧЕЛОВЕК'),
(1, 'BICYCLE - ВЕЛОСИПЕД'),
(2, 'CAR - АВТОМОБИЛЬ'),
(3, 'MOTORCYCLE - МОТОЦИКЛ'),
(4, 'AIRPLANE - САМОЛЕТ'),
(5, 'BUS - АВТОБУС'),
(6, 'TRAIN - ПОЕЗД'),
(7, 'TRUCK - ГРУЗОВИК'),
(8, 'BOAT - ЛОДКА'),
(9, 'TRAFFICLIGHT - СВЕТОФОР'),
(10, 'FIREHYDRANT - ПОЖАРНЫЙ ГИДРАНТ'),
(11, 'STOPSIGN - СТОП-СИГНАЛ'),
(12, 'PARKINGMETER - ПАРКОВОЧНЫЙ СЧЕТЧИК'),
(13, 'BENCH - СКАМЕЙКА'),
(14, 'BIRD - ПТИЦА'),
(15, 'CAT - КОШКА'),
(16, 'DOG - СОБАКА'),
(17, 'HORSE - ЛОШАДЬ'),
(18, 'SHEEP - ОВЦА'),
(19, 'COW - КОРОВА'),
(20, 'ELEPHANT - -СЛОН'),
(21, 'BEAR - МЕДВЕДЬ'),
(22, 'ZEBRA - ЗЕБРА'),
(23, 'GIRAFFE - ЖИРАФ'),
(24, 'BACKPACK - РЮКЗАК'),
(25, 'UMBRELLA - ЗОНТИК'),
(26, 'HANDBAG - СУМКА'),
(27, 'TIE - ГАЛСТУК'),
(28, 'SUITCASE - ЧЕМОДАН'),
(29, 'FRISBEE - ФРИСБИ'),
(30, 'SKIS - ЛЫЖИ'),
(31, 'SNOWBOARD - СНОУБОРД'),
(32, 'SPORTSBALL - СПОРТИВНЫЙ МЯЧ'),
(33, 'KITE - ВОЗДУШНЫЙ ЗМЕЙ'),
(34, 'BASEBALLBAT - БЕЙСБОЛЬНАЯ БИТА'),
(35, 'BASEBALLGLOVE - BASEBALLGLOVE'),
(36, 'SKATEBOARD - СКЕЙТБОРД'),
(37, 'SURFBOARD - ДОСКА ДЛЯ СЕРФИНГА'),
(38, 'TENNISRACKET - ТЕННИСНАЯ РАКЕТКА'),
(39, 'BOTTLE - БУТЫЛКА'),
(40, 'WINEGLASS - БОКАЛ ДЛЯ ВИНА'),
(41, 'CUP - ЧАШКА'),
(42, 'FORK - ВИЛКА'),
(43, 'KNIFE - НОЖ'),
(44, 'SPOON - ЛОЖКА'),
(45, 'BOWL - МИСКА'),
(46, 'BANANA - С БАНАНОМ'),
(47, 'APPLE - ЯБЛОКО'),
(48, 'SANDWICH - СЭНДВИЧ'),
(49, 'ORANGE - ОРАНЖЕВЫЙ'),
(50, 'BROCCOLI - БРОККОЛИ'),
(51, 'CARROT - МОРКОВЬ'),
(52, 'HOTDOG - ХОТ-ДОГ'),
(53, 'PIZZA - ПИЦЦА'),
(54, 'DONUT - ПОНЧИК'),
(55, 'CAKE - ТОРТ'),
(56, 'CHAIR - КРЕСЛО'),
(57, 'COUCH - ДИВАН'),
(58, 'POTTEDPLANT - КОМНАТНОЕ РАСТЕНИЕ'),
(59, 'BED - КРОВАТЬ'),
(60, 'DININGTABLE - ОБЕДЕННЫЙ СТОЛ'),
(61, 'TOILET - ТУАЛЕТ'),
(62, 'TV - ТЕЛЕВИЗОР'),
(63, 'LAPTOP - НОУТБУК'),
(64, 'MOUSE - МЫШЬ'),
(65, 'REMOTE - УДАЛЕННЫЙ'),
(66, 'KEYBOARD - КЛАВИАТУРА'),
(67, 'CELLPHONE - МОБИЛЬНЫЙ ТЕЛЕФОН'),
(68, 'MICROWAVE - МИКРОВОЛНОВАЯ ПЕЧЬ'),
(69, 'OVEN - ДУХОВКА'),
(70, 'TOASTER - ТОСТЕР'),
(71, 'SINK - РАКОВИНА'),
(72, 'REFRIGERATOR - ХОЛОДИЛЬНИК'),
(73, 'BOOK - КНИГА'),
(74, 'CLOCK - ЧАСЫ'),
(75, 'VASE - ВАЗА'),
(76, 'SCISSORS - НОЖНИЦЫ'),
(77, 'TEDDYBEAR - ПЛЮШЕВЫЙ МИШКА'),
(78, 'HAIRDRIER - ПАРИКМАХЕР'),
(79, 'TOOTHBRUSH - ЗУБНАЯ ЩЁТКА'),
)
    put = forms.CharField(label='Путь к папке с фотографиями',
                          widget=forms.TextInput(attrs={'placeholder': 'Путь', 'class': 'form-control'}))
    format = forms.ChoiceField(choices=form, label='Расширение файлов',
                               widget=forms.Select(attrs={'class': 'form-control'}))
    cat = forms.ChoiceField(choices=detect, label='Категория детекции',
                            widget=forms.Select(attrs={'class': 'form-control'}))

