from django import forms

class PhotoFilterForm(forms.Form):
    form = (('jpg', 'JPG'),
            ('jpeg', 'JPEG'),
            ('cr', 'Kodak: CR'),
            ('k25', 'Kodak: K25'),
            ('kdc', 'Kodak: KDC'),
            ('crw', 'Canon: CRW'),
            ('cr2', 'Canon: CR2'),
            ('cr3', 'Canon: CR3'),
            ('erf', 'Epson: ERF'),
            ('nef', 'Nikon: NEF'),
            ('nrw', 'Nikon: NRW'),
            ('orf', 'Olympus: ORF'),
            ('pef', 'Pentax: PEF'),
            ('rw2', 'Panasonic: RW2'),
            ('arw', 'Sony: ARW'),
            ('srf', 'Sony: SRF'),
            ('sr2', 'Sony: SR2'))
    wat = (('quality','Качество фотографий'),
           ('eyes', 'Открытые глаза'))

    wath = forms.ChoiceField(choices=wat, label='Выберите критерии фильтрации',widget=forms.Select(attrs={'class': 'form-control'}))
    put = forms.CharField(label='Путь к папке с фотографиями',widget=forms.TextInput(attrs={'placeholder': 'Путь', 'class': 'form-control'}))
    format = forms.ChoiceField(choices=form, label='Расширение файлов',widget=forms.Select(attrs={'class': 'form-control'}))

class PhotoFaceFilterForm(forms.Form):
    form = (('jpg', 'JPG'),
            ('jpeg', 'JPEG'),
            ('cr', 'Kodak: CR'),
            ('k25', 'Kodak: K25'),
            ('kdc', 'Kodak: KDC'),
            ('crw', 'Canon: CRW'),
            ('cr2', 'Canon: CR2'),
            ('cr3', 'Canon: CR3'),
            ('erf', 'Epson: ERF'),
            ('nef', 'Nikon: NEF'),
            ('nrw', 'Nikon: NRW'),
            ('orf', 'Olympus: ORF'),
            ('pef', 'Pentax: PEF'),
            ('rw2', 'Panasonic: RW2'),
            ('arw', 'Sony: ARW'),
            ('srf', 'Sony: SRF'),
            ('sr2', 'Sony: SR2'))

    detect = (('person', 'PERSON'),
        ('bicycle', 'BICYCLE'),
        ('car', 'CAR'),
        ('motorcycle', 'MOTORCYCLE'),
        ('airplane', 'AIRPLANE'),
        ('bus', 'BUS'),
        ('train', 'TRAIN'),
        ('truck', 'TRUCK'),
        ('boat', 'BOAT'),
        ('trafficlight', 'TRAFFICLIGHT'),
        ('firehydrant', 'FIREHYDRANT'),
        ('stopsign', 'STOPSIGN'),
        ('parkingmeter', 'PARKINGMETER'),
        ('bench', 'BENCH'),
        ('bird', 'BIRD'),
        ('cat', 'CAT'),
        ('dog', 'DOG'),
        ('horse', 'HORSE'),
        ('sheep', 'SHEEP'),
        ('cow', 'COW'),
        ('elephant', 'ELEPHANT'),
        ('bear', 'BEAR'),
        ('zebra', 'ZEBRA'),
        ('giraffe', 'GIRAFFE'),
        ('backpack', 'BACKPACK'),
        ('umbrella', 'UMBRELLA'),
        ('handbag', 'HANDBAG'),
        ('tie', 'TIE'),
        ('suitcase', 'SUITCASE'),
        ('frisbee', 'FRISBEE'),
        ('skis', 'SKIS'),
        ('snowboard', 'SNOWBOARD'),
        ('sportsball', 'SPORTSBALL'),
        ('kite', 'KITE'),
        ('baseballbat', 'BASEBALLBAT'),
        ('baseballglove', 'BASEBALLGLOVE'),
        ('skateboard', 'SKATEBOARD'),
        ('surfboard', 'SURFBOARD'),
        ('tennisracket', 'TENNISRACKET'),
        ('bottle', 'BOTTLE'),
        ('wineglass', 'WINEGLASS'),
        ('cup', 'CUP'),
        ('fork', 'FORK'),
        ('knife', 'KNIFE'),
        ('spoon', 'SPOON'),
        ('bowl', 'BOWL'),
        ('banana', 'BANANA'),
        ('apple', 'APPLE'),
        ('sandwich', 'SANDWICH'),
        ('orange', 'ORANGE'),
        ('broccoli', 'BROCCOLI'),
        ('carrot', 'CARROT'),
        ('hotdog', 'HOTDOG'),
        ('pizza', 'PIZZA'),
        ('donut', 'DONUT'),
        ('cake', 'CAKE'),
        ('chair', 'CHAIR'),
        ('couch', 'COUCH'),
        ('pottedplant', 'POTTEDPLANT'),
        ('bed', 'BED'),
        ('diningtable', 'DININGTABLE'),
        ('toilet', 'TOILET'),
        ('tv', 'TV'),
        ('laptop', 'LAPTOP'),
        ('mouse', 'MOUSE'),
        ('remote', 'REMOTE'),
        ('keyboard', 'KEYBOARD'),
        ('cellphone', 'CELLPHONE'),
        ('microwave', 'MICROWAVE'),
        ('oven', 'OVEN'),
        ('toaster', 'TOASTER'),
        ('sink', 'SINK'),
        ('refrigerator', 'REFRIGERATOR'),
        ('book', 'BOOK'),
        ('clock', 'CLOCK'),
        ('vase', 'VASE'),
        ('scissors', 'SCISSORS'),
        ('teddybear', 'TEDDYBEAR'),
        ('hairdrier', 'HAIRDRIER'),
        ('toothbrush', 'TOOTHBRUSH'),
)
    put = forms.CharField(label='Путь к папке с фотографиями',
                          widget=forms.TextInput(attrs={'placeholder': 'Путь', 'class': 'form-control'}))
    format = forms.ChoiceField(choices=form, label='Расширение файлов',
                               widget=forms.Select(attrs={'class': 'form-control'}))
    cat = forms.ChoiceField(choices=detect, label='Категория детекции',
                            widget=forms.Select(attrs={'class': 'form-control'}))

